datasets:
  - "income"
  - "balance"

tickers:
  - "VRTX"
  - "REGN"
  - "ARGX"
  - "RVMD"
  - "ONC"
  - "RPRX"
  - "ALNY"
  - "ROIV"
  - "INCY"
  - "BNTX"
  - "MRNA"
  - "INSM"
  - "GMAB"
  - "ASND"
  - "JAZZ"
  - "BBIO"
  - "EXEL"
  - "CORT"
  - "ARWR"
  - "BMRN"
  - "TECH"
  - "AXSM"
  - "MDGL"
  - "ABVX"
  - "CYTK"
