tickers:
  - "REGN"
  - "NVCT"
  - "ZBIO"
  - "XNCR"
  - "MPLT"
  - "ALDX"
  - "VBIO"
  - "OTLK"
  - "MIRM"
  - "NAUT"
  - "SPRC"
  - "CYTK"
  - "ADXN"
  - "HURA"
  - "BIOT"
  - "INAB"
  - "LBRX"
  - "ACRV"
  - "UNCY"
  - "ELOX"
  - "MTNB"
  - "KARD"
  - "CTNM"
  - "AGIO"
  - "EIKN"
  - "SLN"
  - "HUMA"
  - "DMAC"
  - "ASND"
  - "ZYME"
  - "AAPG"
  - "MGNX"
  - "SILO"
  - "PHVS"
  - "INSM"
  - "FATE"
  - "IMMX"
  - "APMD"
  - "GRI"
  - "ESLA"
  - "AARD"
  - "JANX"
  - "RNTX"
  - "CRNX"
  - "TNYA"
  - "OABI"
  - "ONC"
  - "OMER"
  - "VRXA"
  - "ANL"
  - "RZLT"
  - "tbph"
  - "FENC"
  - "NRXP"
  - "DMRA"
  - "EXEL"
  - "ARGX"
  - "ASBP"
  - "IMNN"
  - "NXTC"
  - "LONA"
  - "ENVB"
  - "TRVI"
  - "SPRB"
  - "ANTX"
  - "IMUX"
  - "VOGX"
  - "GNTA"
  - "SCNI"
  - "VRDN"
  - "NNVC"
  - "ORMP"
  - "PPCB"
  - "IBIO"
  - "LYEL"
  - "PBLS"
  - "PLRX"
  - "ATAI"
  - "ACXP"
  - "VRTX"
  - "APVO"
  - "NBP"
  - "EYPT"
  - "KLRA"
  - "ENLV"
  - "CRBP"
  - "FBLG"
  - "CLGN"
  - "PLX"
  - "AIM"
  - "CRVO"
  - "BYSI"
  - "FBRX"
  - "KRRO"
  - "TNGX"
  - "KPTI"
  - "RNA"
  - "PROK"
  - "VYGR"
  - "IKT"
  - "SNGX"
