version: 2

models:
  - name: balance_sheet
    description: Contains quarterly balance sheet data.
    columns:
      - name: ticker
      - name: frame_year
      - name: frame_quarter
      - name: quarter_end
      - name: assets
      - name: assets_current
      - name: liabilities
      - name: liabilities_current
      - name: liabilities_and_stockholders_equity
      - name: cash
      - name: cash_and_cash_equivalents_at_carrying_value

  - name: income_statement
    description: Contains quarterly income statement reports.
    columns:
      - name: ticker
      - name: frame_year
      - name: frame_quarter
      - name: quarter_end
