version: 2

models:
  - name: income
    description: "Aggregated company income data"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: revenue
      - name: gross_profit
      - name: operating_income
      - name: net_income
      - name: cost_of_revenue
